load-bal. , web-server, https-ssl

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -1,44 +1,70 @@
 #!/usr/bin/env bash
-# Configures a new ubuntu machine by installing
-# Nginx where it should be listening on port 80
-# Serve a page that would return a Hello World string
-#
-# colors
-blue='\e[1;34m'
-brown='\e[0;33m'
-green='\e[1;32m'
-reset='\033[0m'
+# A script to install nginx on a server
+# - Nginx should be listening on port 80
+# - When querying Nginx at its root / with a GET request (requesting a page) using curl,
+#     it must return a page that contains the string `Hello World!`
+# - Configure Nginx so that its redirecting to another page permanently
+# - Configure Nginx to have a custom 404 page that contains the string `Ceci n'est pas une page`
 
-echo -e "${blue}Updating and installing ${brown}Nginx${blue}.${reset}\n"
-sudo apt-get update -y -qq && \
-	 sudo apt-get install nginx -y
+link="https://www.linkedin.com/in/achrafelkhnissi/"
+config="/etc/nginx/sites-available/default"
+error_file="/var/www/html/404.html"
 
-echo -e "\n${blue}Setting up some minor stuff.${reset}\n"
+# Install nginx
+apt-get -y update
+apt-get -y install nginx
 
-# starting nginx service
-sudo service nginx start
+# Start nginx
+if [[ ! $(pgrep nginx) ]]; then
+    service nginx start
+fi
 
-# allowing nginx on firewall
-sudo ufw allow 'Nginx HTTP'
+# Allow Nginx through the firewall
+ufw allow 'Nginx HTTP'
 
 # Give the user ownership to website files for easy editing
-sudo chown -R "$USER":"$USER" /var/www/html
-sudo chmod -R 755 /var/www
+chown -R "$USER":"$USER" /var/www/html
+chmod -R 755 /var/www
 
-# Backup default index
-cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
+# Get the first root directory of nginx from the configuration file
+root_dir=$(grep "root" /etc/nginx/sites-available/default | cut -d " " -f 2 | tr -d ";" | head -1)
 
-# Creating new index
-echo -e "Hello World!" > /var/www/html/index.nginx-debian.html
+# Create the directory if it doesn't exist
+if [[ ! -d $root_dir ]]; then
+    sudo mkdir -p "$root_dir"
+fi
 
-# Setting up /redirect_me to a youtube video
-sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
+# Write `Hello World!` to the index.html file
+echo "Hello World!" > "$root_dir"/index.html
 
-# Set up a 404 page
-echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
-sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
+# Check if Nginx is running and serving the expected content
+response=$(curl -s http://localhost)
+if [[ $response == "Hello World!" ]]; then
+  echo "Nginx installation and configuration successful!"
+else
+  echo "Nginx installation or configuration failed."
+  exit 1
+fi
 
-# Restarting nginx
-sudo service nginx restart
+# Configure Nginx to redirect to another page permanently with a 301 Moved Permanently HTTP response
+sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://linkedin.com/in/achrafelkhnissi/ permanent;" $config
 
-echo -e "\n${green}Completed.${reset} ✅\n"
+# Configure Nginx to have a custom 404 page that contains the string `Ceci n'est pas une page`
+
+echo "Ceci n'est pas une page" > "$error_file"
+sed -i "/listen 80 default_server;/a error_page 404 /404.html; location = /404.html {root  /var/www/html;\n internal;}" $config
+
+# Check if the configuration is valid
+if nginx -t | grep "successful"; then
+  echo "Nginx configuration failed."
+  exit 1
+fi
+
+# Reload Nginx
+nginx -s reload
+
+# Restart Nginx
+service nginx restart
+
+# Check if Nginx is redirecting to the expected page
+exit 0
